### ISSUE TITLE
fix database of inventory

### ISSUE THREAD

**Issue by stiesssh** [t2-project/inventory#2]
Currently the inventory service uses one database only, which is the database of the CD. As a result, all the products etc. are placed in that database. Preferrably the inventory would connect to two seperate DBs:
- the CD database for the transactional outboxing pattern and
- another DB for the domain data (products, reservation, etc.)

**Comment by davidkopp** [comment]
The saga implementation of the T2-Project relies on the [transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html), so the domain data and the outbox table must be in the same database. Otherwise, the atomicity of the local transaction can't be guaranteed.

Therefore, this issue should not be about using two different databases for the Inventory service, but using one separate Eventuate Postgres database per service that participates in the saga (Inventory, Order, Payment and Orchestrator service). The CDC service then has to poll not only one database, but multiple ones.

However, there is one more issue: the order service uses MongoDB, that is not supported by the Eventuate Tram framework and btw the usage of local transactions are not recommended by the MongoDB community. At the moment the order service writes its business data to its MongoDB and sends out Saga messages to Kafka in a non-transactional way (transactional outbox pattern is not used).

The payment service that also participates in the saga, doesn't need a database for domain data. Therefore, the transactional outbox pattern is actually not relevant for it. Nevertheless, with the current configuration the payment service uses the same database as the others to write messages into it.

**Comment by davidkopp** [comment]
Resolved with merge commit https://github.com/t2-project/devops/commit/83c1b805de75d6b908b8dee8ed6f840d58e9a5df

First work was done in https://github.com/t2-project/devops/pull/2
